name: Generate Checksum for Shell Scripts

on:
  push:
    paths:
      - '**.sh'

jobs:
  generate-checksum:
    runs-on: ubuntu-latest
    env:
      BOT_NAME: ${{vars.BOT_NAME }}
      BOT_EMAIL: ${{vars.BOT_EMAIL}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checksums
        run: |
          if [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]; then
            changed_files=$(git ls-files '*.sh')
          else
            changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.sh$' || true)
          fi

          if [ -z "$changed_files" ]; then
            exit 0
          fi

          echo "$changed_files" | while IFS= read -r file; do
            if [ -n "$file" ] && [ -f "$file" ]; then
              sha256sum "$file" | awk '{print $1}' > "${file}.sha256"
            fi
          done

          git config --local user.email "$BOT_EMAIL"
          git config --local user.name "$BOT_NAME"
          git add *.sha256 **/*.sha256 || true

          if git diff --staged --quiet; then
            exit 0
          fi

          git commit -m "Updated SHA256 checksums"
          git push
